### ISSUE TITLE
Face Recognition ERROR

### ISSUE THREAD

**Issue by bmarhiv** [EbenKouao/MMM-Face-Recognition-SMAI#8]
Hello,

When I'm starting the MagicMirror after intalling the Face Recognition Module,
I'm getting the following error.

[06.09.2021 13:07.04.043] [INFO]  Checking git for module: MMM-Face-Recognition-SMAI
[06.09.2021 13:07.05.003] [INFO]  Calendar-Fetcher: Broadcasting 5 events.
[06.09.2021 13:07.05.253] [INFO]  Newsfeed-Fetcher: Broadcasting 51 items.
[06.09.2021 13:07.06.385] [ERROR] Whoops! There was an uncaught exception...
[06.09.2021 13:07.06.400] [ERROR] ReferenceError: face_rec_name is not defined
    at /home/pi/MagicMirror/modules/MMM-Face-Recognition-SMAI/node_helper.js:38:12
    at FSReqCallback.oncomplete (fs.js:160:23)
[06.09.2021 13:07.06.405] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[06.09.2021 13:07.06.413] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[06.09.2021 13:07.06.430] [ERROR] Whoops! There was an uncaught exception...
[06.09.2021 13:07.06.435] [ERROR] ReferenceError: face_rec_name is not defined
    at /home/pi/MagicMirror/modules/MMM-Face-Recognition-SMAI/node_helper.js:38:12
    at FSReqCallback.oncomplete (fs.js:160:23)

Can you help me please ?

**Comment by jag-k** [comment]
@bmarhiv did you save your face image with this format: `<YourName>-id.png`?
